### ISSUE TITLE
Joints/Limbs sometimes remain in visualization after a person leaves the Kinect field-of-view

### ISSUE THREAD

**Issue by rossmead** [semio-robotics/semio_ros#14] opened 2016-09-25 10:18 UTC
<img width="960" alt="body parts left behind" src="https://cloud.githubusercontent.com/assets/150612/18817327/9b7e4be0-8312-11e6-8845-0b70809fef18.png">

We also saw the same effect for a second tracked person (in which case, it flickered between colors, as per issue #13).

**Comment by ekaszubski** [comment] 2016-09-25 19:14
Screenshot is of out-of-date code due to issue with test build 1 for #11 (now fixed). If the issue still exists, please post a new screenshot. Thanks!

**Comment by rossmead** [comment] 2016-09-25 19:17
Unfortunately, we're still getting the same issue, even after the most recent update (see version info below).

Version: 0.7.2-0+pr11-1 with
294d8e1cd1324c7004c1ef9c9924ad31  /usr/lib/x86_64-linux-gnu/libsemio_visualization_ros.so
6a835a840e3bde8e50a99983e9b5dada  /usr/lib/semio_visualization_ros/semio_visualization_server_node

**Comment by ekaszubski** [comment] 2016-09-25 19:17
Can you please post a screenshot as requested?

**Comment by ekaszubski** [comment] 2016-09-25 19:18
Also, if possible, please verify whether any non-empty humanoids are being published by your humanoid source during the time the bug occurs

**Comment by rossmead** [comment] 2016-09-25 19:19
Send the command(s) you want us to run.

**Comment by ekaszubski** [comment] 2016-09-25 19:21
`rostopic echo <humanoids topic>`

**Comment by rossmead** [comment] 2016-09-26 04:13
<img width="960" alt="phantom limbs" src="https://cloud.githubusercontent.com/assets/150612/18822390/213d7df4-8364-11e6-9ab3-2ccf862ce66e.png">

^ Updated screenshot (seconds after most recent image in #13).

Tried to verify if there were non-empty humanoids being published, but can't seem to echo Humanoid messages.  Thoughts?

**Comment by ekaszubski** [comment] 2016-09-26 17:02
Thanks for the updated screenshot. Confirmed using NiTE2 UserViewer sample that this is most likely being caused by NiTE temporarily tracking something else near you in the frame when you walk out. 

Options to fix:
1. Require some minimum number/set of joints to constitute a humanoid being returned by HumanoidSourceNiTE
2. Require some minimum number/set of joints to constitute a humanoid being visualized by VisualizationAdapterHumanoid
3. Something else?

I think my preference is (1) because it will reduce confusion in other components of the system. Thoughts?

**Comment by ekaszubski** [comment] 2016-09-27 00:07
Tracking in [libsemio #35](https://github.com/semio-robotics/libsemio/issues/35)

**Comment by ekaszubski** [comment] 2016-09-28 22:48
Needs new repro with [libsemio >= 1.16.1](https://github.com/semio-robotics/libsemio/releases/latest) and [libsemio-ros >= 0.8.0](https://github.com/semio-robotics/semio_ros/releases/latest)

**Comment by ekaszubski** [comment] 2016-10-01 15:03
Moving this to the [CRI: Attention: Nice-to-have](https://github.com/semio-robotics/semio_ros/milestone/3) milestone since it has had no recent activity. Will close after [CRI: Attention: Nice-to-have](https://github.com/semio-robotics/semio_ros/milestone/3) expires.

**Comment by rossmead** [comment] 2016-10-02 00:39
![leftover humanoid limbs](https://cloud.githubusercontent.com/assets/150612/19017800/786aef56-87fd-11e6-81ae-58a221c89345.png)

When I step out of the frame, it looks like some of the joints (legs and/or arms?) are popping up with a confidence of 0.5, which must be why they're still showing up.  Maybe if the "required" NiTE joints aren't available, set the confidence for all other joints to 0.0 for NiTE output and publish at least once (or just force the empty list there).  Weird...

Also, I did somehow manage to get it to be an empty list at one point, but I haven't been able to recreate that.

Hopefully this helps.  Can discuss more as needed.

**Comment by ekaszubski** [comment] 2016-10-02 01:28
Many thanks for the extra debugging. It seems like one or more nodes are ignoring the tracking state of the humanoid, which should be set to TrackingState::NONE when the confidence requirements in HumanoidSourceNiTE are not met. Can you verify whether the tracking state of the humanoid is actually set to NONE when this issue pops up?

**Comment by ekaszubski** [comment] 2016-10-02 17:14
It has been confirmed that the tracking state is being set correctly; looking through other components for incorrect handling of tracking state.

**Comment by ekaszubski** [comment] 2016-10-03 06:12
Found multiple places where tracking state was not being checked; these have been fixed in #27. Please try to repro with the latest test build in #27. Thanks!

**Comment by ekaszubski** [comment] 2016-10-03 17:40
Appears to be fixed by #27; please re-open if this pops up again.

**Closed as completed by ekaszubski** 2016-10-03 17:40 UTC
Labels: bug, needs repro
